src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return redirect()
		->route('dashboard');
});

Auth::routes();
Route::get('register', function() {
	return abort(404);
});

Route::middleware(['auth'])
	->group(function () {
		Route::resource('profile', 'ProfileController')
			->only([
				'show',
				'edit',
				'update',
			]);

		Route::get('dashboard', 'HomeController@dashboard')
			->name('dashboard');

		Route::resource('clients', 'ClientController')
			->except([
				'destroy',
			]);
		Route::prefix('clients')
			->name('clients.')
			->group(function() {
				Route::resource('contacts', 'ClientContactController')
					->except([
						'index',
						'show',
						'create',
					]);
				Route::get('contacts/create/{clientId}', 'ClientContactController@create')
					->name('contacts.create');

				Route::resource('conversations', 'ClientConversationController')
					->except([
						'index',
						'show',
						'create',
					]);
				Route::get('conversations/create/{clientId}', 'ClientConversationController@create')
					->name('conversations.create');
			});

		Route::prefix('financial')
			->name('financial.')
			->group(function() {
				Route::resource('invoices', 'InvoiceController');
				Route::get('invoices/status/{status}', 'InvoiceController@index')
					->name('invoices.index.status');
				Route::get('invoices/{invoiceId}/download', 'InvoiceController@download')
					->name('invoices.download');
				Route::get('invoices/{invoiceId}/clone', 'InvoiceController@clone')
					->name('invoices.clone');

				Route::resource('recurring-invoices', 'RecurringInvoiceController');
				Route::get('recurring-invoices/{recurringInvoiceId}/clone', 'RecurringInvoiceController@clone')
					->name('recurring-invoices.clone');

				Route::resource('quotes', 'QuoteController');
				Route::get('quotes/status/{status}', 'QuoteController@index')
					->name('quotes.index.status');
				Route::get('quotes/{quoteId}/download', 'QuoteController@download')
					->name('quotes.download');
				Route::get('quotes/{quoteId}/convert', 'QuoteController@convert')
					->name('quotes.convert');
				Route::get('quotes/{quoteId}/clone', 'QuoteController@clone')
					->name('quotes.clone');

				Route::resource('expenses', 'ExpenseController');

				Route::resource('invoice-category', 'InvoiceCategoryController');
				Route::resource('expense-category', 'ExpenseCategoryController');
				Route::resource('payment-methods', 'PaymentMethodController');
			});

		Route::resource('users', 'UserController');

		Route::prefix('settings')
			->name('settings.')
			->group(function() {
				Route::get('index', 'SettingController@index')
					->name('index');
				Route::put('update', 'SettingController@update')
					->name('update');
				Route::get('flushcache', 'SettingController@flushCache')
					->name('flushcache');
			});

		Route::get('reports', 'ReportController@index')
			->name('reports');
	});

src/app/RecurringInvoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Carbon\Carbon;

class RecurringInvoice extends Model
{
	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'client_id',
		'client_contact_id',
		'invoice_category_id',
		'start_date',
		'end_date',
		'recurring_frequency',
		'recurring_period',
		'recurring_invoice_number',
		'discount',
		'template',
		'label',
	];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		//
	];

	public static function boot() {
        parent::boot();

        self::creating(function($model){
            if (!$model->template) {
				$model->template = settings('default_invoice_template');
			}
        });

        self::created(function($model){
            // ... code here
        });

        self::updating(function($model){
            // ... code here
        });

        self::updated(function($model){
            // ... code here
        });

        self::deleting(function($model){
            // ... code here
        });

        self::deleted(function($model){
            // ... code here
        });
    }

	public function client() {
		return $this->belongsTo('App\Client');
	}

	public function items() {
		return $this->hasMany('App\RecurringInvoiceItem');
	}

	public function category() {
		return $this->belongsTo('App\InvoiceCategory', 'invoice_category_id');
	}

	public function nextDate() {
		$recurringFrequency = $this->recurring_frequency;
		$recurringPeriod = $this->recurring_period;

		$start = Carbon::parse($this->start_date, settings('timezone'));
		$end = $this->end_date != null ? Carbon::parse($this->end_date, settings('timezone')) : null;
		$today = Carbon::today(settings('timezone'));
		$nextDate = $start;

		if ($end && $today > $end) {
			return null;
		}

		while ($nextDate < $today) {
			$nextDate = $nextDate->add($recurringFrequency. ' ' .$recurringPeriod);
		}

		return $nextDate;
	}

	public function totalWithoutDiscount($numeric = false) {
		$total = 0;

		foreach ($this->items as $item) {
			$total += $item->total(true);
		}

		if ($numeric) {
			return $total;
		}

		return settings('default_currency'). " " .number_format($total, 2, settings('comma_seperator'), settings('thousands_seperator'));
	}

	public function total($numeric = false) {
		$total = $this->totalWithoutDiscount(true);

		if ($numeric) {
			return $total*(100-$this->discount)/100;
		}

		return settings('default_currency'). " " .number_format($total*(100-$this->discount)/100, 2, settings('comma_seperator'), settings('thousands_seperator'));
	}
}

src/app/Http/Controllers/RecurringInvoiceController.php
<?php
// TODO: Implement

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

use Validator;
use Carbon\Carbon;

use App\Tmp;
use App\RecurringInvoice;
use App\InvoiceCategory;
use App\Client;
use App\Unit;
use App\Invoice;
use App\InvoiceItem;
use App\RecurringInvoiceItem;
use App\User;
use App\Mail\InvoiceGenerated;

class RecurringInvoiceController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		$recurringInvoices = RecurringInvoice::orderBy('id', 'desc')->paginate(10);
		foreach ($recurringInvoices as $recurringInvoice) {
			$recurringInvoice->last_date = $recurringInvoice->last_date ? Carbon::parse($recurringInvoice->last_date)->format(settings('dateformat')) : 'never';
			$recurringInvoice->start_date = Carbon::parse($recurringInvoice->start_date)->format(settings('dateformat'));
			$recurringInvoice->end_date = $recurringInvoice->end_date ? Carbon::parse($recurringInvoice->end_date)->format(settings('dateformat')) : '';
		}

		$crontabError = false;
		$lastCrontab = Tmp::where('key', 'last_crontab')->first();
		if (!$lastCrontab or !$lastCrontab->value or Carbon::parse($lastCrontab->value)->diffInMinutes(Carbon::now()) > 16) {
			$crontabError = true;
		}

		return view('recurring-invoices.index', [
			'recurringInvoices' => $recurringInvoices,
			'crontabError' => $crontabError,
		]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('recurring-invoices.create', [
			'clients' => Client::all(),
			'invoiceCategories' => InvoiceCategory::all(),
		]);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$validator = Validator::make($request->all(), [
			'client_id' => 'required|exists:clients,id',
			'invoice_category_id' => 'required|exists:invoice_categories,id',
			'start_date' => 'date',
			'end_date' => 'date|nullable',
			'recurring_frequency' => 'numeric',
			'recurring_period' => 'in:days,weeks,months,years',
		]);

		if ($validator->fails()) {
			return redirect()
				->back()
				->withErrors($validator)
				->withInput();
		}

		$recurringInvoice = new RecurringInvoice;
		$recurringInvoice->client_id = $request->client_id;
		$recurringInvoice->invoice_category_id = $request->invoice_category_id;
		$recurringInvoice->discount = Client::find($request->client_id)->default_discount;
		$recurringInvoice->start_date = $request->start_date;
		$recurringInvoice->end_date = $request->end_date;
		$recurringInvoice->recurring_frequency = $request->recurring_frequency;
		$recurringInvoice->recurring_period = $request->recurring_period;

		$recurringInvoice->save();

		return redirect()
			->route('financial.recurring-invoices.edit', [$recurringInvoice->id]);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		return redirect(route('financial.recurring-invoices.edit', [$id]));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		$recurringInvoice = RecurringInvoice::findOrFail($id);
		$recurringInvoice->last_date = $recurringInvoice->last_date ? Carbon::parse($recurringInvoice->last_date)->format(settings('dateformat')) : 'never';

		return view('recurring-invoices.edit', [
			'recurringInvoice' => $recurringInvoice,
			'clients' => Client::all(),
			'invoiceCategories' => InvoiceCategory::all(),
			'units' => Unit::all(),
			'templates' => Invoice::templates(),
		]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$validator = Validator::make($request->all(), [
			'client_id' => 'required|exists:clients,id',
			'client_contact_id' => 'nullable|exists:client_contacts,id',
			'discount' => 'nullable',
			'start_date' => 'date',
			'end_date' => 'nullable',
			'invoice_category_id' => 'required|exists:invoice_categories,id',
			'template' => 'required',
			'label' => '',
			'recurring_frequency' => 'numeric',
			'recurring_period' => 'in:days,weeks,months,years',
			'*.*.name' => 'required',
			'*.*.description' => 'nullable',
			'*.*.quantity' => 'required|numeric',
			'*.*.unit_id' => 'required|exists:units,id',
			'*.*.price' => 'required|numeric',
		]);

		if ($validator->fails()) {
			return redirect()
				->back()
				->withErrors($validator)
				->withInput();
		}

		$recurringInvoice = RecurringInvoice::findOrFail($id);
		$recurringInvoice->discount = $request->discount;

		if ($recurringInvoice->client_id != $request->client_id) {
			if (!$recurringInvoice->discount) {
				$recurringInvoice->discount = Client::find($request->client_id)->default_discount;
			}
		}

		$recurringInvoice->client_id = $request->client_id;
		$recurringInvoice->client_contact_id = $request->client_contact_id;
		$recurringInvoice->start_date = $request->start_date;
		$recurringInvoice->end_date = $request->end_date;
		$recurringInvoice->invoice_category_id = $request->invoice_category_id;
		$recurringInvoice->recurring_frequency = $request->recurring_frequency;
		$recurringInvoice->recurring_period = $request->recurring_period;
		$recurringInvoice->template = $request->template;
		$recurringInvoice->label = $request->label;

		if (!$request->end_date) {
			$recurringInvoice->end_date = null;
		}

		$recurringInvoice->save();

		$recurringInvoice->items()->delete();

		if ($request->items) {
			foreach ($request->items as $item) {
				$invoiceItem = new RecurringInvoiceItem;
				$invoiceItem->recurring_invoice_id = $id;
				$invoiceItem->unit_id = $item['unit_id'];
				$invoiceItem->name = $item['name'];
				$invoiceItem->description = $item['description'];
				$invoiceItem->quantity = $item['quantity'];
				$invoiceItem->price = $item['price'];
				$invoiceItem->save();
			}
		}

		if ($request->new) {
			foreach ($request->new as $item) {
				$invoiceItem = new RecurringInvoiceItem;
				$invoiceItem->recurring_invoice_id = $id;
				$invoiceItem->unit_id = $item['unit_id'];
				$invoiceItem->name = $item['name'];
				$invoiceItem->description = $item['description'];
				$invoiceItem->quantity = $item['quantity'];
				$invoiceItem->price = $item['price'];
				$invoiceItem->save();
			}
		}

		return redirect()
			->route('financial.recurring-invoices.edit', [$id])
			->withSuccess('Recurring Invoice updated.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		RecurringInvoice::destroy($id);
		return redirect()
			->route('financial.recurring-invoices.index')
			->withSuccess('Recurring Invoice deleted.');
	}

	/**
	 * Clone the speciied resource.
	 * 
	 * @param  int $recurringInvoiceId
	 * @return \Illuminate\Http\Response
	 */
	public function clone($recurringInvoiceId) {
		$recurringInvoices = RecurringInvoice::findOrFail($recurringInvoiceId);
		
		$new = $recurringInvoices->replicate();
		$new->save();
		
		foreach ($recurringInvoices->items as $item) {
			$newItem = $item->replicate();
			$newItem->recurring_invoice_id = $new->id;
			$newItem->save();
		}	

		return redirect(route('financial.recurring-invoices.edit', [ $new->id ]));
	}

	/**
	 * Checks if new invoices need to be created
	 * 
	 */
	public function checkRecurringInvoices() {
		$recurringInvoices = RecurringInvoice::all();
		$today = Carbon::today(settings('timezone'));

		foreach ($recurringInvoices as $recurringInvoice) {
			if ($recurringInvoice->nextDate() == $today) {
				$lastDate = Carbon::parse($recurringInvoice->last_date, settings('timezone'));

				if ($lastDate != $today) {
					$recurringInvoice->last_date = $today;
					$recurringInvoice->save();
					$due_date = $today->addDays(settings('invoice_due_within'));

					$lastInvoiceNumber = lastInvoiceNumber();
					
					$invoice = new Invoice;
					$invoice->client_id = $recurringInvoice->client_id;
					$invoice->client_contact_id = $recurringInvoice->client_contact_id;
					$invoice->invoice_category_id = $recurringInvoice->invoice_category_id;
					$invoice->invoice_status = 'draft';
					$invoice->invoice_date = $today;
					$invoice->invoice_number = generateInvoiceNumber(++$lastInvoiceNumber);
					$invoice->due_date = $due_date;
					$invoice->discount = $recurringInvoice->discount;
					$invoice->template = $recurringInvoice->template;
					$invoice->label = $recurringInvoice->label;
					$invoice->recurring_invoice_id = $recurringInvoice->id;
					$invoice->save();

					foreach ($recurringInvoice->items as $recurringInvoiceItem) {
						$invoiceItem = new InvoiceItem;
						$invoiceItem->invoice_id = $invoice->id;
						$invoiceItem->unit_id = $recurringInvoiceItem->unit_id;
						$invoiceItem->name = $recurringInvoiceItem->name;
						$invoiceItem->description = $recurringInvoiceItem->description;
						$invoiceItem->quantity = $recurringInvoiceItem->quantity;
						$invoiceItem->price = $recurringInvoiceItem->price;
						$invoiceItem->vat1 = $recurringInvoiceItem->vat1;
						$invoiceItem->vat2 = $recurringInvoiceItem->vat2;
						$invoiceItem->save();
					}

					echo "Invoice {$invoice->invoice_number} created.\n";

					$superAdmins = User::where('super_user', 1)->get();

					foreach ($superAdmins as $user){
						Mail::to($user)
							->queue(new InvoiceGenerated($invoice));

						if (Mail::failures()) {
							var_dump(Mail::failures());
						}
						
						echo "Super admins have been notified.\n";
					}
				}
			}
		}
	}
}

src/resources/views/recurring-invoices/edit.blade.php
@extends('_layouts.app')
@section('title', 'Recurring Invoice #' .str_pad($recurringInvoice->id, settings('leading_zeroes'), '0', STR_PAD_LEFT))

@section('content')
	<form id="destroyForm" action="{{ route('financial.recurring-invoices.destroy', [$recurringInvoice->id]) }}" method="post">
		@csrf
		@method('delete')
	</form>

	<form action="{{ route('financial.recurring-invoices.update', [$recurringInvoice->id]) }}" method="post">
		@csrf
		@method('PUT')

		<div class="col-lg-12">
			@include('_partials.alerts')

			<div class="panel panel-default">
				<div class="panel-heading">
					General Data

					<a class="pull-right panel-settings" href="#" onclick="event.preventDefault();$('#destroyForm').submit();" title="Delete">
						<span class="fa fa-times"></span>
					</a>

					<a class="pull-right panel-settings" href="{{ route('financial.recurring-invoices.clone', [$recurringInvoice->id]) }}" title="Duplicate">
						<span class="fa fa-clone"></span>
					</a>
				</div>

				<div class="panel-body">
					<div class="col-md-6">
						<div class="form-group">
							<label>Recurring Invoice Number</label>

							<input type="text" class="form-control" value="{{ str_pad($recurringInvoice->id, settings('leading_zeroes'), '0', STR_PAD_LEFT) }}" disabled>
						</div>

						<div class="form-group {{ $errors->has('client_id') ? 'has-error' : '' }}">
							<label>Client</label>
							<small>required</small>

							<select class="form-control" name="client_id" required>
								@foreach ($clients as $client)
									<option value="{{ $client->id }}" {{ old('client_id') == $client->id ? 'selected' : $recurringInvoice->client_id == $client->id ? 'selected' : '' }}>
										{{ $client->company_name }}
										@if($client->default_discount && $client->default_discount != 0)
											({{ $client->default_discount }}% default discount)
										@endif
									</option>
								@endforeach
							</select>
						</div>

						<div class="form-group {{ $errors->has('client_contact_id') ? 'has-error' : '' }}">
							<label>Contact</label>

							<select class="form-control" name="client_contact_id">
								<option {{ old('client_contact_id') ? $recurringInvoice->client_contact_id ? '' : 'selected' : 'selected' }} disabled></option>
								@foreach ($recurringInvoice->client->contacts as $contact)
									<option value="{{ $contact->id }}" {{ old('client_contact_id') == $contact->id ? 'selected' : $recurringInvoice->client_contact_id == $contact->id ? 'selected' : '' }}>{{ $contact->firstname . ' ' . $contact->name }}</option>
								@endforeach
							</select>
						</div>

						<div class="form-group {{ $errors->has('discount') ? 'has-error' : '' }}">
							<label>Discount</label>

							<input type="number" class="form-control" name="discount" value="{{ old('discount') ? old('discount') : $recurringInvoice->discount }}">
						</div>

						<div class="form-group {{ $errors->has('template') ? 'has-error' : '' }}">
							<label>Template</label>

							<select class="form-control" name="template">
								@foreach ($templates as $template)
									<option value="{{ $template }}" {{ old('template') == $template ? 'selected' : $recurringInvoice->template == $template ? 'selected' : '' }}>{{ $template }}</option>
								@endforeach
							</select>
						</div>

						<div class="form-group">
							<label>Next Date</label>

							<input type="text" class="form-control" value="{{ $recurringInvoice->nextDate()->format(settings('dateformat')) }} (Last Date: {{ $recurringInvoice->last_date }})" disabled>
						</div>
					</div>

					<div class="col-md-6">
						<div class="form-group {{ $errors->has('start_date') ? 'has-error' : '' }}">
							<label>Start Date</label>

							<input type="date" class="form-control" name="start_date" value="{{ old('start_date') ? old('start_date') : $recurringInvoice->start_date }}">
						</div>

						<div class="form-group {{ $errors->has('end_date') ? 'has-error' : '' }}">
							<label>End Date</label>

							<input type="date" class="form-control" name="end_date" value="{{ old('end_date') ? old('end_date') : $recurringInvoice->end_date }}">
						</div>

						<div class="form-group {{ $errors->has('invoice_category_id') ? 'has-error' : '' }}">
							<label>Invoice Category</label>
							<small>required</small>

							<select class="form-control" name="invoice_category_id" required>
								@foreach ($invoiceCategories as $category)
									<option value="{{ $category->id }}" {{ old('invoice_category_id') == $category->id ? 'selected' : $recurringInvoice->invoice_category_id == $category->id ? 'selected' : '' }}>{{ $category->number . ' ' . $category->description }}</option>
								@endforeach
							</select>
						</div>

						<div class="form-group {{ $errors->has('recurring_frequency') ? 'has-error' : '' }}">
							<label>Recurring Frequency</label>
							<small>required</small>
							<input type="number" required class="form-control" name="recurring_frequency" value="{{ old('recurring_frequency') ? old('recurring_frequency') : $recurringInvoice->recurring_frequency }}">
						</div>

						<div class="form-group {{ $errors->has('recurring_period') ? 'has-error' : '' }}">
							<label>Recurring Period</label>
							<small>required</small>

							<select class="form-control" name="recurring_period" required>
								<option value="days" {{ old('recurring_period') == 'days' ? 'selected' : $recurringInvoice->recurring_period == 'days' ? 'selected' : '' }}>Days</option>
								<option value="weeks" {{ old('recurring_period') == 'weeks' ? 'selected' : $recurringInvoice->recurring_period == 'weeks' ? 'selected' : '' }}>Weeks</option>
								<option value="months" {{ old('recurring_period') == 'months' ? 'selected' : $recurringInvoice->recurring_period == 'months' ? 'selected' : '' }}>Months</option>
								<option value="years" {{ old('recurring_period') == 'years' ? 'selected' : $recurringInvoice->recurring_period == 'years' ? 'selected' : '' }}>Years</option>
							</select>
						</div>

						<div class="form-group {{ $errors->has('label') ? 'has-error' : '' }}">
							<label>Custom Label</label>

							<input type="text" class="form-control" name="label" value="{{ old('label') ? old('label') : $recurringInvoice->label }}" placeholder="COPY, DUPLICATE, ...">
						</div>
					</div>

					<div class="col-md-12">
						<button type="submit" class="btn btn-primary">Save changes</button>
					</div>
				</div>
			</div>
		</div>

		<div class="col-lg-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Items
				</div>

				<div class="panel-body">
					<div class="col-md-12">
						<div class="table-responsive">
							<table class="table table-hover">
								<thead>
									<tr>
										<th>Name</th>
										<th>Description</th>
										<th>Quantity</th>
										<th>Unit</th>
										<th>Price ({{ settings('default_currency') }})</th>
										<th class="text-right">Total</th>
										<td></td>
									</tr>
								</thead>
								<tbody id="items">
									@foreach ($recurringInvoice->items as $item)
										<tr>
											<td>
												<div class="form-group {{ $errors->has('items.' .$item->id. 'name') ? 'has-error' : '' }}">
													<input type="text" class="form-control" name="items[{{ $item->id }}][name]" value="{{ old('items.' .$item->id. '.name') ? old('items.' .$item->id. '.name') : $item->name }}" required>
												</div>
											</td>

											<td>
												<div class="form-group {{ $errors->has('items.' .$item->id. 'description') ? 'has-error' : '' }}">
													<textarea name="items[{{ $item->id }}][description]" class="form-control">{{ old('items.' .$item->id. '.description') ? old('items.' .$item->id. '.description') : $item->description }}</textarea>
												</div>
											</td>

											<td>
												<div class="form-group {{ $errors->has('items.' .$item->id. 'quantity') ? 'has-error' : '' }}">
													<input type="number" step="0.01" class="form-control text-right quantity" name="items[{{ $item->id }}][quantity]" value="{{ old('items.' .$item->id. '.quantity') ? old('items.' .$item->id. '.quantity') : $item->quantity }}" required>
												</div>
											</td>

											<td>
												<div class="form-group {{ $errors->has('items.' .$item->id. 'unit_id') ? 'has-error' : '' }}">
													<select class="form-control" name="items[{{ $item->id }}][unit_id]" required>
														@foreach ($units as $unit)
															<option value="{{ $unit->id }}" {{ old('items.' .$item->id. '.unit_id') == $unit->id ? 'selected' : $item->unit_id == $unit->id ? 'selected' : '' }}>{{ $unit->name }}</option>
														@endforeach
													</select>
												</div>
											</td>

											<td>
												<div class="form-group {{ $errors->has('items.' .$item->id. 'price') ? 'has-error' : '' }}">
													<input type="number" step="0.01" class="form-control text-right price" name="items[{{ $item->id }}][price]" value="{{ old('items.' .$item->id. '.price') ? old('items.' .$item->id. '.price') : $item->price }}" required>
												</div>
											</td>

											<td class="text-right row-total">
												{{ $item->total() }}
											</td>

											<td class="deleteRow" style="cursor: pointer;" title="Delete">
												<span class="fa fa-times"></span>
											</td>
										</tr>
									@endforeach
								</tbody>

								<tfoot>
									<tr class="text-center" id="newline" style="cursor: pointer;">
										<td colspan="7">
											<span class="fa fa-plus" title="Create"></span>
										</td>
									</tr>

									<tr>
										<td class="text-right" colspan="5">
											Subtotal<br>
											Discount<br>
											<span style="font-weight: bold">
												Total
											</span>
										</td>
										<td class="text-right">
											{{ $recurringInvoice->totalWithoutDiscount() }}<br>
											{{ number_format($recurringInvoice->discount, 2, settings('comma_seperator'), settings('thousands_seperator')) }}%<br>
											<span style="font-weight: bold">
												{{ $recurringInvoice->total() }}
											</span>
										</td>
										<td></td>
									</tr>
								</tfoot>
							</table>
						</div>
					</div>

					<div class="col-md-12">
						<button type="submit" class="btn btn-primary">Save changes</button>
					</div>
				</div>
			</div>
		</div>
	</form>
@endsection

@section('scripts')
	<script>
		$(document).on('click', ".deleteRow",function() {
			$(this).closest('tr').remove();
		});

		var newCounter = 0;
		$('#newline').click(function(e) {
			e.preventDefault();
			++newCounter;

			$('#items').append('<tr><td><div class="form-group"><input type="text" class="form-control" name="new[' + newCounter + '][name]" required></div></td><td><div class="form-group"><textarea name="new[' + newCounter + '][description]" class="form-control"></textarea></div></td><td><div class="form-group"><input type="number" step="0.01" class="form-control text-right" name="new[' + newCounter + '][quantity]" required value="1"></div></td><td><div class="form-group"><select class="form-control" name="new[' + newCounter + '][unit_id]" required>@foreach ($units as $unit)<option value="{{ $unit->id }}">{{ $unit->name }}</option>@endforeach</select></div></td><td><div class="form-group"><input type="number" step="0.01" class="form-control text-right" name="new[' + newCounter + '][price]" required></div></td><td class="text-right"></td><td class="deleteRow" style="cursor: pointer;" title="Delete"><span class="fa fa-times"></span></td></tr>');
		});

		function updateAmounts(row) {
			$(row).each(function() {
				var quantity = $(this).find('.quantity').val();
				var price = $(this).find('.price').val();
				var amount = (quantity*price)
				$(this).find('.row-total').text('{{ settings('default_currency') }} ' + $.number(amount, 2, '{{ settings('comma_seperator') }}', '{{ settings('thousands_seperator') }}'));
			});
		}

		$('input[name*="price"]').on('keyup', function() {
			updateAmounts($(this).closest('tr'));
		});

		$('input[name*="quantity"]').on('keyup', function() {
			updateAmounts($(this).closest('tr'));
		});
	</script>
@endsection