src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return redirect()
		->route('dashboard');
});

Auth::routes();
Route::get('register', function() {
	return abort(404);
});

Route::middleware(['auth'])
	->group(function () {
		Route::resource('profile', 'ProfileController')
			->only([
				'show',
				'edit',
				'update',
			]);

		Route::get('dashboard', 'HomeController@dashboard')
			->name('dashboard');

		Route::resource('clients', 'ClientController')
			->except([
				'destroy',
			]);
		Route::prefix('clients')
			->name('clients.')
			->group(function() {
				Route::resource('contacts', 'ClientContactController')
					->except([
						'index',
						'show',
						'create',
					]);
				Route::get('contacts/create/{clientId}', 'ClientContactController@create')
					->name('contacts.create');

				Route::resource('conversations', 'ClientConversationController')
					->except([
						'index',
						'show',
						'create',
					]);
				Route::get('conversations/create/{clientId}', 'ClientConversationController@create')
					->name('conversations.create');
			});

		Route::prefix('financial')
			->name('financial.')
			->group(function() {
				Route::resource('invoices', 'InvoiceController');
				Route::get('invoices/status/{status}', 'InvoiceController@index')
					->name('invoices.index.status');
				Route::get('invoices/{invoiceId}/download', 'InvoiceController@download')
					->name('invoices.download');
				Route::get('invoices/{invoiceId}/clone', 'InvoiceController@clone')
					->name('invoices.clone');

				Route::resource('recurring-invoices', 'RecurringInvoiceController');
				Route::get('recurring-invoices/{recurringInvoiceId}/clone', 'RecurringInvoiceController@clone')
					->name('recurring-invoices.clone');

				Route::resource('quotes', 'QuoteController');
				Route::get('quotes/status/{status}', 'QuoteController@index')
					->name('quotes.index.status');
				Route::get('quotes/{quoteId}/download', 'QuoteController@download')
					->name('quotes.download');
				Route::get('quotes/{quoteId}/convert', 'QuoteController@convert')
					->name('quotes.convert');
				Route::get('quotes/{quoteId}/clone', 'QuoteController@clone')
					->name('quotes.clone');

				Route::resource('expenses', 'ExpenseController');

				Route::resource('invoice-category', 'InvoiceCategoryController');
				Route::resource('expense-category', 'ExpenseCategoryController');
				Route::resource('payment-methods', 'PaymentMethodController');
			});

		Route::resource('users', 'UserController');

		Route::prefix('settings')
			->name('settings.')
			->group(function() {
				Route::get('index', 'SettingController@index')
					->name('index');
				Route::put('update', 'SettingController@update')
					->name('update');
				Route::get('flushcache', 'SettingController@flushCache')
					->name('flushcache');
			});

		Route::get('reports', 'ReportController@index')
			->name('reports');
	});

src/resources/views/clients/modules/show/company.blade.php
<div class="tab-pane fade active in" id="company">
    <div class="col-lg-12">
        <div class="panel-heading">
            General Data

            <a class="pull-right panel-settings" href="{{ route('clients.edit', [$client->id]) }}" title="Edit">
                <span class="fa fa-edit"></span>
            </a>
        </div>

        <div class="panel-body">
            <div class="col-md-6">
                <p>
                    Company Name
                    <span class="form-control">{{ $client->company_name }}</span>
                </p>

                <p>
                    Website
                    <span class="form-control"><a href="{{ $client->website }}">{{ $client->website }}</a></span>
                </p>

                <p>
                    E-Mail
                    <span class="form-control"><a href="mailto:{{ $client->email }}">{{ $client->email }}</a></span>
                </p>
            </div>

            <div class="col-md-6">
                <p>
                    Phone
                    <span class="form-control">{{ $client->phone }}</span>
                </p>

                <p>
                    VAT Number
                    <span class="form-control">{{ $client->vat_number }}</span>
                </p>

                <p>
                    Default Discount
                    <span class="form-control">{{ $client->default_discount ? $client->default_discount : '0' }} %</span>
                </p>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="panel-heading">
            Address
        </div>

        <div class="panel-body">
            <div class="col-md-12">
                <p>
                    {!! nl2br($client->address) !!}<br />
                    {{ $client->address_zip }} {{ $client->address_city }}<br />
                    {{ $client->address_country }}
                </p>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="panel-heading">
            Comments
        </div>

        <div class="panel-body">
            <div class="col-md-12">
                <p>
                    {!! nl2br($client->comments) !!}
                </p>
            </div>
        </div>
    </div>
</div>

src/resources/views/clients/modules/show/contacts.blade.php
<div class="tab-pane fade" id="contacts">
    <div class="panel-heading">
        Contacts

        <a class="pull-right panel-settings" href="{{ route('clients.contacts.create', [$client->id]) }}" title="Create">
            <span class="fa fa-plus"></span>
        </a>
    </div>

    <div class="panel-body">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Firstname</th>
                            <th>Name</th>
                            <th>E-Mail</th>
                            <th>Phone</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($client->contacts as $contact)
                            <tr>
                                <td>{{ $contact->firstname }}</td>
                                <td>{{ $contact->name }}</td>
                                <td>
                                    <a href="mailto:{{ $contact->email }}">{{ $contact->email }}</a>
                                </td>
                                <td>{{ $contact->phone }}</td>
                                <td class="text-right">
                                    <form action="{{ route('clients.contacts.destroy', [$contact->id]) }}" method="post" id="deleteContact{{ $contact->id }}">
                                        @csrf
                                        @method('delete')
                                    </form>

                                    <a class="btn btn-default btn-circle btn-sm margin" href="{{ route('clients.contacts.edit', [$contact->id]) }}"><span class="fa fa-edit"></span></a>
                                    <a class="btn btn-default btn-circle btn-sm margin" href="" onclick="event.preventDefault();$('#deleteContact{{ $contact->id }}').submit();"><span class="fa fa-times"></span></a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

src/resources/views/clients/modules/show/conversations.blade.php
<div class="tab-pane fade" id="conversations">
    <div class="panel-heading">
        Conversations

        <a class="pull-right panel-settings" href="{{ route('clients.conversations.create', [$client->id]) }}" title="Create">
            <span class="fa fa-plus"></span>
        </a>
    </div>

    <div class="panel-body">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Datetime</th>
                            <th>Summary</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($client->conversations as $conversation)
                            <tr>
                                <td>{{ $conversation->type }}</td>
                                <td>{{ $conversation->datetime }}</td>
                                <td>{!! nl2br($conversation->summary) !!}</td>
                                <td class="text-right">
                                    <form action="{{ route('clients.conversations.destroy', [$conversation->id]) }}" method="post" id="deleteConversation{{ $conversation->id }}">
                                        @csrf
                                        @method('delete')
                                    </form>

                                    <a class="btn btn-default btn-circle margin" href="{{ route('clients.conversations.edit', [$conversation->id]) }}"><span class="fa fa-edit"></span></a>
                                    <a class="btn btn-default btn-circle margin" href="" onclick="event.preventDefault();$('#deleteConversation{{ $conversation->id }}').submit();"><span class="fa fa-times"></span></a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

src/resources/views/clients/modules/show/financial.blade.php
<div class="tab-pane fade" id="financial">
    <div class="panel-heading">
        Financial
    </div>

    <div class="panel-body">
        <div class="col-md-6">
            <h4>Invoices</h4>

            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Invoice Date</th>
                            <th>Due Date</th>
                            <th class="text-right">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($client->invoices->sortByDesc('invoice_number') as $invoice)
                            <tr>
                                <td>
                                    <a href="{{ route('financial.invoices.edit', [$invoice->id]) }}">{{ $invoice->invoice_number }}</a>
                                </td>
                                <td>{{ \Carbon\Carbon::parse($invoice->invoice_date)->format(settings('dateformat')) }}</td>
                                <td>{{ \Carbon\Carbon::parse($invoice->due_date)->format(settings('dateformat')) }}</td>
                                <td class="text-right">
                                    {{ $invoice->total() }}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-md-6">
            <h4>Recurring Invoices</h4>

            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Start Date</th>
                            <th>Next Date</th>
                            <th>End Date</th>
                            <th>Every</th>
                            <th class="text-right">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($client->recurringInvoices->sortByDesc('recurring_invoice_number') as $recurringInvoice)
                            <tr>
                                <td>
                                    <a href="{{ route('financial.recurring-invoices.edit', [$recurringInvoice->id]) }}">{{ $recurringInvoice->recurring_invoice_number }}</a>
                                </td>
                                <td>{{ \Carbon\Carbon::parse($recurringInvoice->start_date)->format(settings('dateformat')) }}</td>
                                <td>{!! $recurringInvoice->nextDate() ? $recurringInvoice->nextDate()->format(settings('dateformat')) : '&mdash;' !!}</td>
                                <td>{{ \Carbon\Carbon::parse($recurringInvoice->end_date)->format(settings('dateformat')) }}</td>
                                <td>{{ $recurringInvoice->recurring_frequency }} {{ $recurringInvoice->recurring_period }}</td>
                                <td class="text-right">
                                    {{ $recurringInvoice->total() }}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-md-6">
            <h4>Quotes</h4>

            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Quote Date</th>
                            <th>Expire Date</th>
                            <th class="text-right">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($client->quotes->sortByDesc('quote_number') as $quote)
                            <tr>
                                <td>
                                    <a href="{{ route('financial.quotes.edit', [$quote->id]) }}">{{ $quote->quote_number }}</a>
                                </td>
                                <td>{{ \Carbon\Carbon::parse($quote->quote_date)->format(settings('dateformat')) }}</td>
                                <td>{{ \Carbon\Carbon::parse($quote->expire_date)->format(settings('dateformat')) }}</td>
                                <td class="text-right">
                                    {{ $quote->total() }}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>