src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return redirect()
		->route('dashboard');
});

Auth::routes();
Route::get('register', function() {
	return abort(404);
});

Route::middleware(['auth'])
	->group(function () {
		Route::resource('profile', 'ProfileController')
			->only([
				'show',
				'edit',
				'update',
			]);

		Route::get('dashboard', 'HomeController@dashboard')
			->name('dashboard');

		Route::resource('clients', 'ClientController')
			->except([
				'destroy',
			]);
		Route::prefix('clients')
			->name('clients.')
			->group(function() {
				Route::resource('contacts', 'ClientContactController')
					->except([
						'index',
						'show',
						'create',
					]);
				Route::get('contacts/create/{clientId}', 'ClientContactController@create')
					->name('contacts.create');

				Route::resource('conversations', 'ClientConversationController')
					->except([
						'index',
						'show',
						'create',
					]);
				Route::get('conversations/create/{clientId}', 'ClientConversationController@create')
					->name('conversations.create');
			});

		Route::prefix('financial')
			->name('financial.')
			->group(function() {
				Route::resource('invoices', 'InvoiceController');
				Route::get('invoices/status/{status}', 'InvoiceController@index')
					->name('invoices.index.status');
				Route::get('invoices/{invoiceId}/download', 'InvoiceController@download')
					->name('invoices.download');
				Route::get('invoices/{invoiceId}/clone', 'InvoiceController@clone')
					->name('invoices.clone');

				Route::resource('recurring-invoices', 'RecurringInvoiceController');
				Route::get('recurring-invoices/{recurringInvoiceId}/clone', 'RecurringInvoiceController@clone')
					->name('recurring-invoices.clone');

				Route::resource('quotes', 'QuoteController');
				Route::get('quotes/status/{status}', 'QuoteController@index')
					->name('quotes.index.status');
				Route::get('quotes/{quoteId}/download', 'QuoteController@download')
					->name('quotes.download');
				Route::get('quotes/{quoteId}/convert', 'QuoteController@convert')
					->name('quotes.convert');
				Route::get('quotes/{quoteId}/clone', 'QuoteController@clone')
					->name('quotes.clone');

				Route::resource('expenses', 'ExpenseController');

				Route::resource('invoice-category', 'InvoiceCategoryController');
				Route::resource('expense-category', 'ExpenseCategoryController');
				Route::resource('payment-methods', 'PaymentMethodController');
			});

		Route::resource('users', 'UserController');

		Route::prefix('settings')
			->name('settings.')
			->group(function() {
				Route::get('index', 'SettingController@index')
					->name('index');
				Route::put('update', 'SettingController@update')
					->name('update');
				Route::get('flushcache', 'SettingController@flushCache')
					->name('flushcache');
			});

		Route::get('reports', 'ReportController@index')
			->name('reports');
	});

src/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
	use Notifiable;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'name',
		'firstname',
		'email',
		'password',
		'mailserver_password',
		'super_user',
	];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		'password',
		'remember_token',
	];
}

src/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Validator;
use Auth;

use App\User;

class UserController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		return view('users.index', [
			'users' => User::paginate(10),
		]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('users.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$validator = Validator::make($request->all(), [
			'firstname' => 'required|min:3',
			'name' => 'required|min:3',
			'email' => 'required|email',
			'mailserver_password' => 'nullable',
			'password' => 'min:8|confirmed|required'
		]);

		if ($validator->fails()) {
			return redirect()
				->back()
				->withErrors($validator)
				->withInput();
		}

		$user = new User;
		$user->firstname = $request->firstname;
		$user->name = $request->name;
		$user->email = $request->email;
		$user->mailserver_password = $request->mailserver_password;
		$user->password = bcrypt($request->password);
		$user->save();

		return redirect()
			->route('users.show', [$user->id])
			->withSuccess('Created new user.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		return view('users.show', [
			'user' => User::findOrFail($id),
		]);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		return view('users.edit', [
			'user' => User::findOrFail($id),
		]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$validator = Validator::make($request->all(), [
			'firstname' => 'required|min:3',
			'name' => 'required|min:3',
			'email' => 'required|email',
			'mailserver_password' => 'nullable',
			'password' => 'min:8|confirmed|nullable',
			'super_user' => 'in:1|nullable',
		]);

		if ($validator->fails()) {
			return redirect()
				->back()
				->withErrors($validator)
				->withInput();
		}

		if (User::where('super_user', '1')->count() <= 1 && !$request->super_user) {
			return redirect()
				->back()
				->withError('You need at least one super user.')
				->withInput();
		}

		$user = User::findOrFail($id);
		$user->firstname = $request->firstname;
		$user->name = $request->name;
		$user->email = $request->email;
		$user->mailserver_password = $request->mailserver_password;
		$user->super_user = $request->super_user ? 1 : 0;

		if (!empty(trim($request->password))) {
			$user->password = bcrypt($request->password);
		}

		$user->save();

		return redirect()
			->route('users.show', [$id])
			->withSuccess('Updated user.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		$user = User::findOrFail($id);
		$email = $user->email;

		if ($user->id == Auth::user()->id) {
			return redirect()
				->route('users.index')
				->withError('You can\'t delete yourself.');
		}

		$user->delete();

		return redirect()
			->route('users.index')
			->withSuccess('Deleted user ' .$email .'.');
	}
}

src/resources/views/users/create.blade.php
@extends('_layouts.app')
@section('title', 'Add New User')

@section('content')
	<form action="{{ route('users.store') }}" method="post">
		@csrf

		<div class="col-lg-12">
			@include('_partials.alerts')

			<div class="panel panel-default">
				<div class="panel-heading">
					Enter User Data
				</div>

				<div class="panel-body">
					<div class="col-md-6">
						<div class="form-group {{ $errors->has('firstname') ? 'has-error' : '' }}">
							<label>Firstname</label>
							<small>required</small>

							<input type="text" class="form-control" name="firstname" value="{{ old('firstname') ? old('firstname') : '' }}" required>
						</div>

						<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
							<label>Name</label>
							<small>required</small>

							<input type="text" class="form-control" name="name" value="{{ old('name') ? old('name') : '' }}" required>
						</div>
					</div>

					<div class="col-md-6">
						<div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
							<label>E-Mail</label>
							<small>required</small>

							<input type="email" class="form-control" name="email" value="{{ old('email') ? old('email') : '' }}" required>
						</div>

						<div class="form-group {{ $errors->has('mailserver_password') ? 'has-error' : '' }}">
							<label>Mailserver Password</label>
							<input type="password" class="form-control" name="mailserver_password" value="{{ old('mailserver_password') ? old('mailserver_password') : '' }}">
						</div>
					</div>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					Password
				</div>

				<div class="panel-body">
					<div class="col-md-6">
						<div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
							<label>Password</label>
							<small>required</small>
							
							<input type="password" class="form-control " name="password" value="{{ old('password') ? old('password') : '' }}" required>
						</div>
					</div>

					<div class="col-md-6">
						<div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}">
							<label>Password Confirmation</label>
							<small>required</small>

							<input type="password" class="form-control" name="password_confirmation" required>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-12">
			<button type="submit" class="btn btn-primary">Create</button>
		</div>
	</form>
@endsection

src/resources/views/users/edit.blade.php
@extends('_layouts.app')
@section('title', 'Edit User')

@section('content')
	<form id="destroyForm" action="{{ route('users.destroy', [$user->id]) }}" method="post">
		@csrf
		@method('delete')
	</form>

	<form action="{{ route('users.update', [$user->id]) }}" method="post">
		@csrf
		@method('PUT')

		<div class="col-lg-12">
			@include('_partials.alerts')

			<div class="panel panel-default">
				<div class="panel-heading">
					{{ $user->firstname }} {{ $user->name }}

					<a class="pull-right panel-settings" href="#" onclick="event.preventDefault();$('#destroyForm').submit();" title="Delete">
						<span class="fa fa-times"></span>
					</a>
				</div>

				<div class="panel-body">
					<div class="col-md-6">
						<div class="form-group {{ $errors->has('firstname') ? 'has-error' : '' }}">
							<label>Firstname</label>
							<small>required</small>

							<input type="text" class="form-control" name="firstname" value="{{ old('firstname') ? old('firstname') : $user->firstname }}" required>
						</div>

						<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
							<label>Name</label>
							<small>required</small>

							<input type="text" class="form-control" name="name" value="{{ old('name') ? old('name') : $user->name }}" required>
						</div>

						<div class="form-group {{ $errors->has('super_user') ? 'has-error' : '' }}">
							<label>
								<input type="checkbox" name="super_user" value="1" {{ old('super_user') ? 'checked' : $user->super_user ? 'checked' : '' }}>
							
								Super User?
								<small>Super users receive notifications and have all permissions.</small>
							</label>
						</div>
					</div>

					<div class="col-md-6">
						<div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
							<label>E-Mail</label>
							<small>required</small>
							
							<input type="email" class="form-control" name="email" value="{{ old('email') ? old('email') : $user->email }}" required>
						</div>

						<div class="form-group {{ $errors->has('mailserver_password') ? 'has-error' : '' }}">
							<label>Mailserver Password</label>
							<input type="password" class="form-control" name="mailserver_password" value="{{ old('mailserver_password') ? old('mailserver_password') : $user->mailserver_password }}">
						</div>
					</div>

					<div class="col-md-12">
						<button type="submit" class="btn btn-primary">Save changes</button>
					</div>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					Change Password
				</div>

				<div class="panel-body">
					<div class="col-md-6">
						<div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
							<label>Password</label>
							<input type="password" class="form-control " name="password" value="{{ old('password') ? old('password') : '' }}">
						</div>
					</div>

					<div class="col-md-6">
						<div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}">
							<label>Password Confirmation</label>
							<input type="password" class="form-control" name="password_confirmation">
						</div>
					</div>

					<div class="col-md-12">
						<button type="submit" class="btn btn-primary">Save changes</button>
					</div>
				</div>
			</div>
		</div>
	</form>
@endsection

src/resources/views/users/index.blade.php
@extends('_layouts.app')
@section('title', 'Users')

@section('content')
	<div class="col-lg-12">
		@include('_partials.alerts')

		<div class="panel panel-default">
			<div class="panel-heading">
				Users <small>({{ $users->total() }})</small>

				<a class="pull-right panel-settings" href="{{ route('users.create') }}" title="Create">
					<span class="fa fa-plus"></span>
				</a>
			</div>

			<div class="panel-body">
				<div class="col-md-12">
					<div class="table-responsive">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>User ID</th>
									<th>Name</th>
									<th>Firstname</th>
									<th>E-Mail</th>
									<th>Super User</th>
								</tr>
							</thead>
							<tbody>
								@foreach ($users as $user)
									<tr>
										<td>
											<a href="{{ route('users.show', [$user->id]) }}">
												{{ $user->id }}
											</a>
										</td>
										<td>{{ $user->name }}</td>
										<td>{{ $user->firstname }}</td>
										<td>
											<a href="mailto:{{ $user->email }}">{{ $user->email }}</a>
										</td>

										<td>
											{{ $user->super_user ? 'Yes' : 'No' }}
										</td>

										<td class="text-right">
											<form action="{{ route('users.destroy', [$user->id]) }}" method="post" id="deleteConversation{{ $user->id }}">
												@csrf
												@method('delete')
											</form>

											<a class="btn btn-default btn-circle btn-sm margin" href="{{ route('users.edit', [$user->id]) }}"><span class="fa fa-edit"></span></a>
											<a class="btn btn-default btn-circle btn-sm margin" href="" onclick="event.preventDefault();$('#deleteConversation{{ $user->id }}').submit();"><span class="fa fa-times"></span></a>
										</td>
									</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>

				<div class="col-md-12 text-center">
					{{ $users->links() }}
				</div>
			</div>
		</div>
	</div>
@endsection

src/resources/views/users/show.blade.php
@extends('_layouts.app')
@section('title', 'View User')

@section('content')
	<div class="col-lg-12">
		@include('_partials.alerts')

		<div class="panel panel-default">
			<div class="panel-heading">
				{{ $user->firstname }} {{ $user->name }}

				<a class="pull-right panel-settings" href="{{ route('users.edit', [$user->id]) }}" title="Edit">
					<span class="fa fa-edit"></span>
				</a>
			</div>

			<div class="panel-body">
				<div class="col-md-6">
					<p>
						Firstname
						<span class="form-control">{{ $user->firstname }}</span>
					</p>

					<p>
						Name
						<span class="form-control">{{ $user->name }}</span>
					</p>

					<p>
						Super User?
						<span class="form-control">
							{{ $user->super_user ? 'Yes' : 'No' }}
						</span>
					</p>
				</div>

				<div class="col-md-6">
					<p>
						E-Mail
						<span class="form-control"><a href="mailto:{{ $user->email }}">{{ $user->email }}</a></span>
					</p>

					<p>
						Profile
						<span class="form-control"><a href="{{ route('profile.show', [$user->email]) }}">{{ route('profile.show', [$user->email]) }}</a></span>
					</p>
				</div>
			</div>
		</div>
	</div>
@endsection