src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return redirect()
		->route('dashboard');
});

Auth::routes();
Route::get('register', function() {
	return abort(404);
});

Route::middleware(['auth'])
	->group(function () {
		Route::resource('profile', 'ProfileController')
			->only([
				'show',
				'edit',
				'update',
			]);

		Route::get('dashboard', 'HomeController@dashboard')
			->name('dashboard');

		Route::resource('clients', 'ClientController')
			->except([
				'destroy',
			]);
		Route::prefix('clients')
			->name('clients.')
			->group(function() {
				Route::resource('contacts', 'ClientContactController')
					->except([
						'index',
						'show',
						'create',
					]);
				Route::get('contacts/create/{clientId}', 'ClientContactController@create')
					->name('contacts.create');

				Route::resource('conversations', 'ClientConversationController')
					->except([
						'index',
						'show',
						'create',
					]);
				Route::get('conversations/create/{clientId}', 'ClientConversationController@create')
					->name('conversations.create');
			});

		Route::prefix('financial')
			->name('financial.')
			->group(function() {
				Route::resource('invoices', 'InvoiceController');
				Route::get('invoices/status/{status}', 'InvoiceController@index')
					->name('invoices.index.status');
				Route::get('invoices/{invoiceId}/download', 'InvoiceController@download')
					->name('invoices.download');
				Route::get('invoices/{invoiceId}/clone', 'InvoiceController@clone')
					->name('invoices.clone');

				Route::resource('recurring-invoices', 'RecurringInvoiceController');
				Route::get('recurring-invoices/{recurringInvoiceId}/clone', 'RecurringInvoiceController@clone')
					->name('recurring-invoices.clone');

				Route::resource('quotes', 'QuoteController');
				Route::get('quotes/status/{status}', 'QuoteController@index')
					->name('quotes.index.status');
				Route::get('quotes/{quoteId}/download', 'QuoteController@download')
					->name('quotes.download');
				Route::get('quotes/{quoteId}/convert', 'QuoteController@convert')
					->name('quotes.convert');
				Route::get('quotes/{quoteId}/clone', 'QuoteController@clone')
					->name('quotes.clone');

				Route::resource('expenses', 'ExpenseController');

				Route::resource('invoice-category', 'InvoiceCategoryController');
				Route::resource('expense-category', 'ExpenseCategoryController');
				Route::resource('payment-methods', 'PaymentMethodController');
			});

		Route::resource('users', 'UserController');

		Route::prefix('settings')
			->name('settings.')
			->group(function() {
				Route::get('index', 'SettingController@index')
					->name('index');
				Route::put('update', 'SettingController@update')
					->name('update');
				Route::get('flushcache', 'SettingController@flushCache')
					->name('flushcache');
			});

		Route::get('reports', 'ReportController@index')
			->name('reports');
	});

src/app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use \Carbon\Carbon;
use Storage;

class Invoice extends Model
{
	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'invoice_status',
		'client_id',
		'client_contact_id',
		'quote_id',
		'recurring_invoice_id',
		'invoice_category_id',
		'invoice_date',
		'invoice_number',
		'due_date',
		'discount',
		'template',
		'label',
	];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		//
	];

	public static function boot() {
        parent::boot();

        self::creating(function($model){
            if (!$model->template) {
				$model->template = settings('default_invoice_template');
			}
        });

        self::created(function($model){
            // ... code here
        });

        self::updating(function($model){
            // ... code here
        });

        self::updated(function($model){
            // ... code here
        });

        self::deleting(function($model){
            // ... code here
        });

        self::deleted(function($model){
            // ... code here
        });
    }

	public function items() {
		return $this->hasMany('App\InvoiceItem');
	}

	public function transactions() {
		return $this->hasMany('App\InvoiceTransaction');
	}

	public function client() {
		return $this->belongsTo('App\Client');
	}

	public function clientContact() {
		return $this->belongsTo('App\ClientContact');
	}

	public function quote() {
		return $this->belongsTo('App\Quote');
	}

	public function recurringInvoice() {
		return $this->belongsTo('App\RecurringInvoice');
	}

	public function category() {
		return $this->belongsTo('App\InvoiceCategory', 'invoice_category_id');
	}

	public function unit() {
		return $this->belongsTo('App\Unit');
	}

	public function dueInDays() {
		$invoiceDate = Carbon::parse($this->invoice_date);
		$dueDate = Carbon::parse($this->due_date);

		return ($invoiceDate->diffInDays($dueDate));
	}

	public function totalWithoutDiscount($numeric = false) {
		$total = 0;

		foreach ($this->items as $item) {
			$total += $item->total(true);
		}

		if ($numeric) {
			return $total;
		}

		return settings('default_currency'). " " .number_format($total, 2, settings('comma_seperator'), settings('thousands_seperator'));
	}

	public function total($numeric = false) {
		$total = $this->totalWithoutDiscount(true);

		if ($numeric) {
			return $total*(100-$this->discount)/100;
		}

		return settings('default_currency'). " " .number_format($total*(100-$this->discount)/100, 2, settings('comma_seperator'), settings('thousands_seperator'));
	}

	public static function templates() {
		$templates = Storage::disk('custom_templates')->files('invoices/');

		foreach ($templates as $key => $value) {
			$templates[$key] = str_replace('.blade.php', '', str_replace('invoices/', '', $value));
			if ($templates[$key] == ".gitignore") {
				unset($templates[$key]);
			}
		}

		return $templates;
	}
}

src/app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Validator;
use Carbon\Carbon;
use PDF;

use App\Invoice;
use App\Client;
use App\InvoiceCategory;
use App\Unit;
use App\InvoiceItem;

class InvoiceController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index($status = null)
	{
		if (!$status) {
			$invoices = Invoice::orderBy('invoice_number', 'desc')->paginate(10);
		}

		if ($status) {
			if ($status == 'overdue') {
				$invoices = Invoice::where('due_date', '<', Carbon::now(settings('timezone'))->toDateString())->where('invoice_status', 'sent')->orderBy('invoice_number', 'desc')->paginate(10);
			} else {
				$invoices = Invoice::where('invoice_status', $status)->orderBy('invoice_number', 'desc')->paginate(10);
			}
		}

		foreach ($invoices as $invoice) {
			if ($invoice->due_date < Carbon::now(settings('timezone'))->toDateString() && $invoice->invoice_status == 'sent') {
				$invoice->overdue = true;
			}
			$invoice->invoice_date = Carbon::parse($invoice->invoice_date)->format(settings('dateformat'));
			$invoice->due_date = Carbon::parse($invoice->due_date)->format(settings('dateformat'));
		}

		return view('invoices.index', [
			'invoices' => $invoices,
		]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		$lastInvoiceNumber = lastInvoiceNumber();

		return view('invoices.create', [
			'clients' => Client::all(),
			'invoiceCategories' => InvoiceCategory::all(),
			'invoiceNumber' => generateInvoiceNumber(++$lastInvoiceNumber),
		]);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$validator = Validator::make($request->all(), [
			'invoice_number' => 'nullable|unique:invoices,invoice_number',
			'client_id' => 'required|exists:clients,id',
			'invoice_date' => 'nullable',
			'invoice_category_id' => 'required|exists:invoice_categories,id',
		]);

		if ($validator->fails()) {
			return redirect()
				->back()
				->withErrors($validator)
				->withInput();
		}

		$invoice = new Invoice;
		$invoice->client_id = $request->client_id;
		$invoice->invoice_date = $request->invoice_date;
		$invoice->invoice_category_id = $request->invoice_category_id;
		$invoice->discount = Client::find($request->client_id)->default_discount;
		$invoice->invoice_number = $request->invoice_number;

		if ($request->invoice_date) {
			$invoice->due_date = Carbon::parse($request->invoice_date)->addDays(settings('invoice_due_within'));
		}

		$invoice->save();

		return redirect()
			->route('financial.invoices.edit', [$invoice->id]);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		return redirect(route('financial.invoices.edit', [$id]));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		if (empty(Invoice::findOrFail($id)->invoice_number) or !Invoice::findOrFail($id)->invoice_number) {
			$invoiceNumber = lastInvoiceNumber();
			$invoiceNumber = generateInvoiceNumber(++$invoiceNumber);
		} else {
			$invoiceNumber = Invoice::findOrFail($id)->invoice_number;
		}

		return view('invoices.edit', [
			'invoice' => Invoice::findOrFail($id),
			'clients' => Client::all(),
			'invoiceCategories' => InvoiceCategory::all(),
			'units' => Unit::all(),
			'invoiceNumber' => $invoiceNumber,
			'templates' => Invoice::templates(),
		]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$validator = Validator::make($request->all(), [
			'invoice_number' => 'nullable',
			'client_id' => 'required|exists:clients,id',
			'client_contact_id' => 'nullable|exists:client_contacts,id',
			'discount' => 'nullable',
			'invoice_date' => 'nullable',
			'due_date' => 'nullable',
			'invoice_category_id' => 'required|exists:invoice_categories,id',
			'invoice_status' => 'required',
			'template' => 'required',
			'label' => '',
			'*.*.name' => 'required',
			'*.*.description' => 'nullable',
			'*.*.quantity' => 'required|numeric',
			'*.*.unit_id' => 'required|exists:units,id',
			'*.*.price' => 'required|numeric',
		]);

		if ($validator->fails()) {
			return redirect()
				->back()
				->withErrors($validator)
				->withInput();
		}

		$invoiceWithIdenticalInvoiceNumber = Invoice::where('invoice_number', $request->invoice_number)->first();

		if ($invoiceWithIdenticalInvoiceNumber && $invoiceWithIdenticalInvoiceNumber->id != $id) {
			return redirect()
				->back()
				->withError('Invoice number already in use.')
				->withInput();
		}

		$invoice = Invoice::findOrFail($id);
		$invoice->discount = $request->discount;

		if ($invoice->client_id != $request->client_id) {
			if (!$request->discount) {
				$invoice->discount = Client::find($request->client_id)->default_discount;
			}
		}

		$invoice->invoice_number = $request->invoice_number;
		$invoice->client_id = $request->client_id;
		$invoice->client_contact_id = $request->client_contact_id;
		$invoice->invoice_date = $request->invoice_date;
		$invoice->due_date = $request->due_date;
		$invoice->invoice_category_id = $request->invoice_category_id;
		$invoice->invoice_status = $request->invoice_status;
		$invoice->template = $request->template;
		$invoice->label = $request->label;

		if (!$request->invoice_date) {
			$invoice->due_date = null;
		}

		if ($request->invoice_date && !$request->due_date) {
			$invoice->due_date = Carbon::parse($request->invoice_date)->addDays(settings('invoice_due_within'));
		}

		$invoice->save();

		$invoice->items()->delete();

		if ($request->items) {
			foreach ($request->items as $item) {
				$invoiceItem = new InvoiceItem;
				$invoiceItem->invoice_id = $id;
				$invoiceItem->unit_id = $item['unit_id'];
				$invoiceItem->name = $item['name'];
				$invoiceItem->description = $item['description'];
				$invoiceItem->quantity = $item['quantity'];
				$invoiceItem->price = $item['price'];
				$invoiceItem->save();
			}
		}

		if ($request->new) {
			foreach ($request->new as $item) {
				$invoiceItem = new InvoiceItem;
				$invoiceItem->invoice_id = $id;
				$invoiceItem->unit_id = $item['unit_id'];
				$invoiceItem->name = $item['name'];
				$invoiceItem->description = $item['description'];
				$invoiceItem->quantity = $item['quantity'];
				$invoiceItem->price = $item['price'];
				$invoiceItem->save();
			}
		}

		return redirect()
			->route('financial.invoices.edit', [$id])
			->withSuccess('Invoice updated.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		Invoice::destroy($id);
		return redirect()
			->route('financial.invoices.index')
			->withSuccess('Invoice deleted.');
	}

	/**
	 * Download the specified resource as PDF.
	 *
	 * @param  int  $invoiceId
	 * @return \Illuminate\Http\Response
	 */
	public function download($invoiceId)
	{
		$invoice = Invoice::findOrFail($invoiceId);
		$invoice->invoice_date = Carbon::parse($invoice->invoice_date)->format(settings('dateformat'));
		$invoice->due_date = Carbon::parse($invoice->due_date)->format(settings('dateformat'));

		$template = ($invoice->template ? $invoice->template : settings('default_invoice_template'));

		$pdf = PDF::loadView("customTemplates::invoices.{$template}", [
			'invoice' => $invoice,
		])->setPaper('A4', 'portrait');

		return $pdf->stream($invoice->invoice_number. '.pdf');
	}

	/**
	 * Clone the speciied resource.
	 * 
	 * @param  int $invoiceId
	 * @return \Illuminate\Http\Response
	 */
	public function clone($invoiceId) {
		$lastInvoiceNumber = lastInvoiceNumber();

		$invoice = Invoice::findOrFail($invoiceId);
		$new = $invoice->replicate();

		$new->invoice_number = generateInvoiceNumber(++$lastInvoiceNumber);
		$new->invoice_date = Carbon::now(settings('timezone'));
		$new->due_date = Carbon::parse($new->invoice_date)->addDays(settings('invoice_due_within'));
		$new->invoice_status = "draft";

		$new->save();
		
		foreach ($invoice->items as $item) {
			$new = $item->replicate();
			$new = $item->invoice_id = $new->id;
			$new = $item->save();
		}	

		return redirect(route('financial.invoices.edit', [ $new->id ]));
	}
}

src/resources/views/invoices/edit.blade.php
@extends('_layouts.app')
@section('title', 'Invoice #' .$invoice->invoice_number)

@section('content')
	<form id="destroyForm" action="{{ route('financial.invoices.destroy', [$invoice->id]) }}" method="post">
		@csrf
		@method('delete')
	</form>

	<form action="{{ route('financial.invoices.update', [$invoice->id]) }}" method="post">
		@csrf
		@method('PUT')

		<div class="col-lg-12">
			@include('_partials.alerts')

			<div class="panel panel-default">
				<div class="panel-heading">
					General Data
					@if ($invoice->quote)
						<a href="{{ route('financial.quotes.edit', [$invoice->quote_id]) }}">
							<small>[ Converted from Quote {{ $invoice->quote->quote_number }} ]</small>
						</a>						
					@endif
					@if ($invoice->recurringInvoice)
						<a href="{{ route('financial.recurring-invoices.edit', [$invoice->recurring_invoice_id]) }}">
							<small>[ Converted from Recurring Invoice #{{ str_pad($invoice->recurringInvoice->id, settings('leading_zeroes'), '0', STR_PAD_LEFT) }} ]</small>
						</a>						
					@endif

					<a class="pull-right panel-settings" href="#" onclick="event.preventDefault();$('#destroyForm').submit();" title="Delete">
						<span class="fa fa-times"></span>
					</a>

					<a class="pull-right panel-settings" href="{{ route('financial.invoices.download', [$invoice->id]) }}" title="Export">
						<span class="fa fa-download"></span>
					</a>

					<a class="pull-right panel-settings" href="{{ route('financial.invoices.clone', [$invoice->id]) }}" title="Duplicate">
						<span class="fa fa-clone"></span>
					</a>
				</div>

				<div class="panel-body">
					<div class="col-md-6">
						<div class="form-group {{ $errors->has('invoice_number') ? 'has-error' : '' }}">
							<label>Invoice Number</label>

							<input type="text" class="form-control" name="invoice_number" value="{{ old('invoice_number') ? old('invoice_number') : $invoice->invoice_number }}" placeholder="{{ $invoiceNumber }}">
						</div>

						<div class="form-group {{ $errors->has('client_id') ? 'has-error' : '' }}">
							<label>Client</label>
							<small>required</small>

							<select class="form-control" name="client_id" required>
								@foreach ($clients as $client)
									<option value="{{ $client->id }}" {{ old('client_id') == $client->id ? 'selected' : $invoice->client_id == $client->id ? 'selected' : '' }}>
										{{ $client->company_name }}
										@if($client->default_discount && $client->default_discount != 0)
											({{ $client->default_discount }}% default discount)
										@endif
									</option>
								@endforeach
							</select>
						</div>

						<div class="form-group {{ $errors->has('client_contact_id') ? 'has-error' : '' }}">
							<label>Contact</label>

							<select class="form-control" name="client_contact_id">
								<option {{ old('client_contact_id') ? $invoice->client_contact_id ? '' : 'selected' : 'selected' }} disabled></option>
								@foreach ($invoice->client->contacts as $contact)
									<option value="{{ $contact->id }}" {{ old('client_contact_id') == $contact->id ? 'selected' : $invoice->client_contact_id == $contact->id ? 'selected' : '' }}>{{ $contact->firstname . ' ' . $contact->name }}</option>
								@endforeach
							</select>
						</div>

						<div class="form-group {{ $errors->has('discount') ? 'has-error' : '' }}">
							<label>Discount</label>

							<input type="number" class="form-control" name="discount" value="{{ old('discount') ? old('discount') : $invoice->discount }}">
						</div>

						<div class="form-group {{ $errors->has('template') ? 'has-error' : '' }}">
							<label>Template</label>

							<select class="form-control" name="template">
								@foreach ($templates as $template)
									<option value="{{ $template }}" {{ old('template') == $template ? 'selected' : $invoice->template == $template ? 'selected' : '' }}>{{ $template }}</option>
								@endforeach
							</select>
						</div>
					</div>

					<div class="col-md-6">
						<div class="form-group {{ $errors->has('invoice_date') ? 'has-error' : '' }}">
							<label>Invoice Date</label>

							<input type="date" class="form-control" name="invoice_date" value="{{ old('invoice_date') ? old('invoice_date') : $invoice->invoice_date }}">
						</div>

						<div class="form-group {{ $errors->has('due_date') ? 'has-error' : '' }}">
							<label>Due Date</label>

							<input type="date" class="form-control" name="due_date" value="{{ old('due_date') ? old('due_date') : $invoice->due_date }}">
						</div>

						<div class="form-group {{ $errors->has('invoice_category_id') ? 'has-error' : '' }}">
							<label>Invoice Category</label>
							<small>required</small>

							<select class="form-control" name="invoice_category_id" required>
								@foreach ($invoiceCategories as $category)
									<option value="{{ $category->id }}" {{ old('invoice_category_id') == $category->id ? 'selected' : $invoice->invoice_category_id == $category->id ? 'selected' : '' }}>{{ $category->number . ' ' . $category->description }}</option>
								@endforeach
							</select>
						</div>

						<div class="form-group {{ $errors->has('invoice_status') ? 'has-error' : '' }}">
							<label>Invoice Status</label>
							<small>required</small>

							<select class="form-control" name="invoice_status" required>
								<option value="draft" {{ $invoice->invoice_status == 'draft' ? 'selected' : '' }}>DRAFT</option>
								<option value="sent" {{ $invoice->invoice_status == 'sent' ? 'selected' : '' }}>SENT</option>
								<option value="" disabled>OVERDUE</option>
								<option value="paid" {{ $invoice->invoice_status == 'paid' ? 'selected' : '' }}>PAID</option>
							</select>
						</div>

						<div class="form-group {{ $errors->has('label') ? 'has-error' : '' }}">
							<label>Custom Label</label>

							<input type="text" class="form-control" name="label" value="{{ old('label') ? old('label') : $invoice->label }}" placeholder="COPY, DUPLICATE, ...">
						</div>
					</div>

					<div class="col-md-12">
						<button type="submit" class="btn btn-primary">Save changes</button>
					</div>
				</div>
			</div>
		</div>

		<div class="col-lg-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Items
				</div>

				<div class="panel-body">
					<div class="col-md-12">
						<div class="table-responsive">
							<table class="table table-hover">
								<thead>
									<tr>
										<th>Name</th>
										<th>Description</th>
										<th>Quantity</th>
										<th>Unit</th>
										<th>Price ({{ settings('default_currency') }})</th>
										<th class="text-right">Total</th>
										<td></td>
									</tr>
								</thead>
								<tbody id="items">
									@foreach ($invoice->items as $item)
										<tr>
											<td>
												<div class="form-group {{ $errors->has('items.' .$item->id. 'name') ? 'has-error' : '' }}">
													<input type="text" class="form-control" name="items[{{ $item->id }}][name]" value="{{ old('items.' .$item->id. '.name') ? old('items.' .$item->id. '.name') : $item->name }}" required>
												</div>
											</td>

											<td>
												<div class="form-group {{ $errors->has('items.' .$item->id. 'description') ? 'has-error' : '' }}">
													<textarea name="items[{{ $item->id }}][description]" class="form-control">{{ old('items.' .$item->id. '.description') ? old('items.' .$item->id. '.description') : $item->description }}</textarea>
												</div>
											</td>

											<td>
												<div class="form-group {{ $errors->has('items.' .$item->id. 'quantity') ? 'has-error' : '' }}">
													<input type="number" step="0.01" class="form-control text-right quantity" name="items[{{ $item->id }}][quantity]" value="{{ old('items.' .$item->id. '.quantity') ? old('items.' .$item->id. '.quantity') : $item->quantity }}" required>
												</div>
											</td>

											<td>
												<div class="form-group {{ $errors->has('items.' .$item->id. 'unit_id') ? 'has-error' : '' }}">
													<select class="form-control" name="items[{{ $item->id }}][unit_id]" required>
														@foreach ($units as $unit)
															<option value="{{ $unit->id }}" {{ old('items.' .$item->id. '.unit_id') == $unit->id ? 'selected' : $item->unit_id == $unit->id ? 'selected' : '' }}>{{ $unit->name }}</option>
														@endforeach
													</select>
												</div>
											</td>

											<td>
												<div class="form-group {{ $errors->has('items.' .$item->id. 'price') ? 'has-error' : '' }}">
													<input type="number" step="0.01" class="form-control text-right price" name="items[{{ $item->id }}][price]" value="{{ old('items.' .$item->id. '.price') ? old('items.' .$item->id. '.price') : $item->price }}" required>
												</div>
											</td>

											<td class="text-right row-total">
												{{ $item->total() }}
											</td>

											<td class="deleteRow" style="cursor: pointer;" title="Delete">
												<span class="fa fa-times"></span>
											</td>
										</tr>
									@endforeach
								</tbody>

								<tfoot>
									<tr class="text-center" id="newline" style="cursor: pointer;">
										<td colspan="7">
											<span class="fa fa-plus" title="Create"></span>
										</td>
									</tr>

									<tr>
										<td class="text-right" colspan="5">
											Subtotal<br>
											Discount<br>
											<span style="font-weight: bold">
												Total
											</span>
										</td>
										<td class="text-right">
											{{ $invoice->totalWithoutDiscount() }}<br>
											{{ number_format($invoice->discount, 2, settings('comma_seperator'), settings('thousands_seperator')) }}%<br>
											<span style="font-weight: bold">
												{{ $invoice->total() }}
											</span>
										</td>
										<td></td>
									</tr>
								</tfoot>
							</table>
						</div>
					</div>

					<div class="col-md-12">
						<button type="submit" class="btn btn-primary">Save changes</button>
					</div>
				</div>
			</div>
		</div>
	</form>
@endsection

@section('scripts')
	<script>
		$(document).on('click', ".deleteRow",function() {
			$(this).closest('tr').remove();
		});

		var newCounter = 0;
		$('#newline').click(function(e) {
			e.preventDefault();
			++newCounter;

			$('#items').append('<tr><td><div class="form-group"><input type="text" class="form-control" name="new[' + newCounter + '][name]" required></div></td><td><div class="form-group"><textarea name="new[' + newCounter + '][description]" class="form-control"></textarea></div></td><td><div class="form-group"><input type="number" step="0.01" class="form-control text-right" name="new[' + newCounter + '][quantity]" required value="1"></div></td><td><div class="form-group"><select class="form-control" name="new[' + newCounter + '][unit_id]" required>@foreach ($units as $unit)<option value="{{ $unit->id }}">{{ $unit->name }}</option>@endforeach</select></div></td><td><div class="form-group"><input type="number" step="0.01" class="form-control text-right" name="new[' + newCounter + '][price]" required></div></td><td class="text-right"></td><td class="deleteRow" style="cursor: pointer;" title="Delete"><span class="fa fa-times"></span></td></tr>');
		});

		function updateAmounts(row) {
			$(row).each(function() {
				var quantity = $(this).find('.quantity').val();
				var price = $(this).find('.price').val();
				var amount = (quantity*price)
				$(this).find('.row-total').text('{{ settings('default_currency') }} ' + $.number(amount, 2, '{{ settings('comma_seperator') }}', '{{ settings('thousands_seperator') }}'));
			});
		}

		$('input[name*="price"]').on('keyup', function() {
			updateAmounts($(this).closest('tr'));
		});

		$('input[name*="quantity"]').on('keyup', function() {
			updateAmounts($(this).closest('tr'));
		});
	</script>
@endsection